spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /snmp/api

mybatis:
  mapper-locations:
    - classpath:mybatis/sqlmap/device/*.xml
  type-aliases-package: cn.cloudwiz.dalian.snmp,cn.cloudwiz.dalian.commons.core.orm.mybatis



