spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /snmp/api

#mybatis:
#  mapper-locations:
#    - classpath:mybatis/sqlmap/fetch/*.xml
#    - classpath:mybatis/sqlmap/reports/*.xml
#    - classpath:mybatis/sqlmap/user/*.xml
#    - classpath:mybatis/sqlmap/system/*.xml
#  type-aliases-package: com.clondwiz.billing,org.chaosoft.framework.core.orm.mybatis



