spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/cloudwiz_snmp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true&allowMultiQueries=true

logging:
  level:
    cn.cloudwiz.dalian.snmp: debug

server:
  port: 8090

swagger:
  enable: true

device:
  logo-root: E:/Store/TempLibrary/snmp