logging:
  level:
    cn.cloudwiz.dalian.snmp: info
  file: ./logs/snmp-demo.log

exporter:
  auto-export-cron: 0 */1 * * * ?

remote-config:
  device-path: http://123.206.91.96:8080/_alertd/node_manager/node/ip?token=0f320e7db4a2d8ba0a3229753bf7c90d821479da
  items-path: http://123.206.91.96:8080/_cmdb/ci/1/1/search2
  tsdb-path: http://123.206.91.96:8080/_tsdb
  org-key: 1
  sys-key: 1
  token:
    username: CloudInsight
    password: Cloud
    url: jdbc:mysql://123.206.91.96:3308/grafana